
let html = "";
html += "<div class=\"message\"><div class=\"col_likes\">";
html += "<i class=\"fas fa-arrow-up like-up-not\"></i><div class=\"nb-likes\">00 k</div>";
html += "<i class=\"fas fa-arrow-down like-down-not\"></i></div>";
html += "<section class=\"corp\"><header class=\"author\">posted by "+author+" le "+horodate;
html += "</header><article>";
html += "<header><h3 class=\"title-article\">"+articleTitle+"</h3></header>";
html += "<p class=\"content-article\">"+articleContent+"</p>";
html += "</article></section>";
html += "<div class=\"bloc-commentaire\">";
html += "<div class=\"commentaire\">";
html += "<div class=\"com-likes\">";
html += "<i class=\"fas fa-arrow-up like-up-not like-com\"></i>";
html += "<i class=\"fas fa-arrow-down like-down-not like-com\"></i>";
html += "<div class=\"trait\"></div></div><div class=\"com-main-0\">";
html += "<div>"+author+" "+nblike+" - "+date+"</div>";
html += "<div class=\"com-content\">"+contentComm;
html += "</div></div></div><div class=\"commentaire\">";
html += "<div class=\"com-likes\"><i class=\"fas fa-arrow-up like-up-not like-com\"></i>";
html += "<i class=\"fas fa-arrow-down like-down-not like-com\"></i><div class=\"trait\"></div></div>";
html += "<div class=\"com-main-0\">";
html += "<div>"+author+" "+nblike+" - "+date+"</div>";
html += "<div class=\"com-content\">"+contentComm;
html += "</div><div class=\"commentaire\"><div class=\"com-likes\">";
html += "<i class=\"fas fa-arrow-up like-up-not like-com\"></i>";
html += "<i class=\"fas fa-arrow-down like-down-not like-com\"></i><div class=\"trait\"></div></div>";
html += "<div class=\"com-main-1\"><div>"+author+" "+nblike+" - "+date+"</div>";
html += "<div class=\"com-content\">"+contentComm;
html += "</div></div></div></div></div></div></div>";